remote_theme				: "mmistakes/minimal-mistakes"
minimal_mistakes_skin			: "sunrise"
locale					: "en-US"				
title					: "Tech Blog"
title_separator				: "-"
subtitle				: "Welcome to my tech world!"
masthead_title				: 
name					: &name "Steven Liang"
description				: &description "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url					: https://bullblock.github.io
baseurl					:
repository				: "bullblock/bullblock.github.io"

words_per_minute			: 200
enable_copy_code_button			: true
comments				:
  provider				: false
  discourse				:
    server				: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963		

twitter_username: 
github_username: bullblock
search: true

markdown: kramdown
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Singapore

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   				: "Steven Liang"
  avatar 				: "/assets/images/bio-photo.jpg"
  bio					: "A seasoned IT professional with 27 years of deep infrastructure expertise and exceptional troubleshooting capabilities. Holding CKA/CKS certifications, he excels in cloud-native architectures including Kubernetes, Docker, and containerization across AWS, GCP, and Azure platforms. His extensive background spans complex enterprise environments from Unix/Linux administration to modern cloud-native solutions. At Broadcom/VMware, he delivered Level 3 technical support for Tanzu solutions, resolving critical production issues for APJ clients. Steven's proven track record includes architecting scalable infrastructures, managing 24/7 production systems, and leading technical teams through complex migrations and implementations across banking, trading, and enterprise sectors."
  location				: "Singapore"
  email					: "steven.liang@pm.me"
  links:
    - lable				: "Email"
      icon				: "fas fa-fw fa-envelope-square"
      url				: "mailto:steven.liang@pm.me" 
    - label				: "Linkedin"
      icon				: "fab fa-fw fa-linkedin"
      url				: "https://www.linkedin.com/in/powellcrack"
    - label				: "GitHub"
      icon				: "fab fa-fw fa-github"
      url				: "https://github.com/bullblock"
    - label				: "Medium"
      icon				: "fab fa-fw fa-medium"
      url				: "https://medium.com/@bullblock"

footer:
  links:
    - label				: "Linkedin"
      icon				: "fab fa-fw fa-linkedin"
      url				: "https://www.linkedin.com/in/powellcrack"
    - label				: "GitHub"
      icon				: "fab fa-fw fa-github"
      url				: "https://github.com/bullblock"
    - label				: "Medium"
      icon				: "fab fa-fw fa-medium"
      url				: "https://medium.com/@bullblock"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
